package Frame;

import java.awt.Dimension;
import java.awt.Polygon;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

/**
 * La classe MainFrame è il frame principale dell'applicazione.
 * @author Pierpaolo Casati
 * @version 11.12.2019
 */
public class MainFrame extends javax.swing.JFrame {
    
    /**
     * Frame dell'applicazione.
     */
    private SnowflakeFrame snowflakeFrame = null;
    
    /**
     * Lista poligoni di taglio.
     */
    private List<Polygon> polygons = new ArrayList<Polygon>();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    /**
     * Permette di aprire un determinato sito web.
     * @param url URL del sito web.
     */
    public void goToWebSite(String url){
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        websiteLabel = new javax.swing.JButton();
        websiteSchoolLabel = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(730, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(730, 480));

        infoPanel.setBackground(new java.awt.Color(83, 81, 81));
        infoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Snowflake Generator");

        versionLabel.setBackground(new java.awt.Color(178, 175, 175));
        versionLabel.setForeground(new java.awt.Color(178, 175, 175));
        versionLabel.setText("Version 1.0");

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/snowflake.png"))); // NOI18N

        websiteLabel.setBackground(new java.awt.Color(83, 81, 81));
        websiteLabel.setForeground(new java.awt.Color(255, 255, 255));
        websiteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home.png"))); // NOI18N
        websiteLabel.setText("Website ");
        websiteLabel.setBorderPainted(false);
        websiteLabel.setContentAreaFilled(false);
        websiteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        websiteLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteLabelActionPerformed(evt);
            }
        });

        websiteSchoolLabel.setBackground(new java.awt.Color(83, 81, 81));
        websiteSchoolLabel.setForeground(new java.awt.Color(255, 255, 255));
        websiteSchoolLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mouse.png"))); // NOI18N
        websiteSchoolLabel.setText("CPT Website");
        websiteSchoolLabel.setBorderPainted(false);
        websiteSchoolLabel.setContentAreaFilled(false);
        websiteSchoolLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        websiteSchoolLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteSchoolLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(versionLabel))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(websiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(websiteSchoolLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionLabel)
                .addGap(65, 65, 65)
                .addComponent(websiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(websiteSchoolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(683, Short.MAX_VALUE))
        );

        getContentPane().add(infoPanel, java.awt.BorderLayout.LINE_START);

        menuPanel.setBackground(new java.awt.Color(26, 26, 26));
        menuPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 150));

        newButton.setBackground(new java.awt.Color(26, 26, 26));
        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new.png"))); // NOI18N
        newButton.setToolTipText("New snowflake");
        newButton.setBorderPainted(false);
        newButton.setContentAreaFilled(false);
        newButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        menuPanel.add(newButton);

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/open.png"))); // NOI18N
        openButton.setToolTipText("Open cut point");
        openButton.setBorderPainted(false);
        openButton.setContentAreaFilled(false);
        openButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        menuPanel.add(openButton);

        getContentPane().add(menuPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void websiteLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteLabelActionPerformed
        String url = "http://samtinfo.ch/i17caspie/";
        this.goToWebSite(url);
    }//GEN-LAST:event_websiteLabelActionPerformed

    private void websiteSchoolLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteSchoolLabelActionPerformed
        String url = "https://www.cpttrevano.ti.ch";
        this.goToWebSite(url);
    }//GEN-LAST:event_websiteSchoolLabelActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
       this.setVisible(false);
       this.snowflakeFrame = new SnowflakeFrame();
       this.snowflakeFrame.setSize(1024, 768);
       this.snowflakeFrame.setMinimumSize(new Dimension(1024, 768));
       this.snowflakeFrame.setVisible(true);   
    }//GEN-LAST:event_newButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        JFileChooser open = new JFileChooser();
        File directory = new File("Snowflake template");
        if(directory.exists()){
            open.setCurrentDirectory(directory);
            open.showDialog(null, "Open");
            BufferedReader br = null;
            try {
                File file = open.getSelectedFile();
                if(!file.getAbsolutePath().matches("[^template_][.csv$]")){
                    br = new BufferedReader ( new FileReader (file));
                    List<String[]> list = new ArrayList<>();
                    String line = "";
                    while((line = br.readLine()) != null){
                        String[] array = line.split("; ");
                        list.add(array);
                    }
            
                    int npoints = 0;
                    int[] xpoints;
                    int[] ypoints;

                    int index = 0;

                    for(String[] lines : list){
                        npoints = Integer.parseInt(lines[0]);
                        xpoints = new int[npoints];
                        ypoints = new int[npoints];
                        String x =  lines[1].substring(1, lines[1].length()-1);
                        String y =  lines[2].substring(1, lines[2].length()-1);
                        String[] xs = x.split(" ");
                        String[] ys = y.split(" ");
                        int count = 0;
                        for(int i = 0; i < npoints; i++){
                            xpoints[i] = Integer.parseInt(
                                    xs[i].replace(",", "")
                            );
                            ypoints[i] = Integer.parseInt(
                                    ys[i].replace(",", "")
                            );
                        }
                        ++index;
                        Polygon p = new Polygon(xpoints, ypoints, npoints);
                        this.polygons.add(p);
                    }

                    this.snowflakeFrame = new SnowflakeFrame();
                    this.snowflakeFrame.setPolygons(polygons);
                    this.snowflakeFrame.setSize(1024, 768);
                    this.snowflakeFrame.setMinimumSize(new Dimension(1024, 768));
                    this.snowflakeFrame.setVisible(true);
                }   

            } catch (FileNotFoundException ex) {

            } catch (IOException e) {
            }   
            catch(Exception ex){

            }
        }
    }//GEN-LAST:event_openButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                   UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JButton websiteLabel;
    private javax.swing.JButton websiteSchoolLabel;
    // End of variables declaration//GEN-END:variables
}
