
package Frame;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Polygon;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.batik.svggen.SVGGraphics2DIOException;

/**
 * La classe SnowflakeFrame rappresenta il frame dell'applicazione.
 * @author Pierpaolo Casati
 * @version 12.12.2019
 */
public class SnowflakeFrame extends javax.swing.JFrame {

    /**
     * Creates new form SnowflakeFrame
     */
    public SnowflakeFrame() {
        initComponents();
    }
    
    /**
     * Setter lista poligoni di taglio.
     * @param polygons Lista poligoni di taglio.
     */
    public void setPolygons(List<Polygon> polygons){
        this.snowflakePanel.setPolygons(polygons);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeButtonGroup = new javax.swing.ButtonGroup();
        menuTabbedPane = new javax.swing.JTabbedPane();
        editPanel = new javax.swing.JPanel();
        newPolygonButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        cutButton = new javax.swing.JButton();
        filePanel = new javax.swing.JPanel();
        sizeLabel = new javax.swing.JLabel();
        minSizeRadioButton = new javax.swing.JRadioButton();
        maxSizeRadioButton = new javax.swing.JRadioButton();
        typeImageLabel = new javax.swing.JLabel();
        exportPngButton = new javax.swing.JButton();
        exportSvgButton = new javax.swing.JButton();
        saveCutPolygons = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        snowflakePanel = new Frame.SnowflakePanel();

        sizeButtonGroup.add(this.minSizeRadioButton);
        sizeButtonGroup.add(this.maxSizeRadioButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        menuTabbedPane.setBackground(new java.awt.Color(204, 204, 204));
        menuTabbedPane.setPreferredSize(new java.awt.Dimension(200, 146));

        editPanel.setLayout(new javax.swing.BoxLayout(editPanel, javax.swing.BoxLayout.Y_AXIS));

        newPolygonButton.setText("New");
        newPolygonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPolygonButtonActionPerformed(evt);
            }
        });
        editPanel.add(newPolygonButton);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        editPanel.add(resetButton);

        cutButton.setText("Cut");
        cutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutButtonActionPerformed(evt);
            }
        });
        editPanel.add(cutButton);

        menuTabbedPane.addTab("Edit", editPanel);

        filePanel.setSize(new java.awt.Dimension(50, 100));
        filePanel.setLayout(new javax.swing.BoxLayout(filePanel, javax.swing.BoxLayout.Y_AXIS));

        sizeLabel.setText("Size image (PNG)");
        filePanel.add(sizeLabel);

        minSizeRadioButton.setText("500px");
        minSizeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minSizeRadioButtonActionPerformed(evt);
            }
        });
        filePanel.add(minSizeRadioButton);

        maxSizeRadioButton.setText("1000px");
        maxSizeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxSizeRadioButtonActionPerformed(evt);
            }
        });
        filePanel.add(maxSizeRadioButton);

        typeImageLabel.setText("Type image");
        filePanel.add(typeImageLabel);

        exportPngButton.setText("Export PNG");
        exportPngButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportPngButtonActionPerformed(evt);
            }
        });
        filePanel.add(exportPngButton);

        exportSvgButton.setText("Export SVG");
        exportSvgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportSvgButtonActionPerformed(evt);
            }
        });
        filePanel.add(exportSvgButton);

        saveCutPolygons.setText("Save cut polygons");
        saveCutPolygons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCutPolygonsActionPerformed(evt);
            }
        });
        filePanel.add(saveCutPolygons);

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        filePanel.add(newButton);

        menuTabbedPane.addTab("File", filePanel);

        getContentPane().add(menuTabbedPane, java.awt.BorderLayout.EAST);

        snowflakePanel.setPreferredSize(new java.awt.Dimension(500, 337));
        getContentPane().add(snowflakePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPolygonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPolygonButtonActionPerformed
       this.snowflakePanel.newPolygon();
    }//GEN-LAST:event_newPolygonButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        this.snowflakePanel.reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void cutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutButtonActionPerformed
        this.snowflakePanel.cut();
    }//GEN-LAST:event_cutButtonActionPerformed

    private void minSizeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minSizeRadioButtonActionPerformed
       this.snowflakePanel.setSize(new Dimension(500, 500));
    }//GEN-LAST:event_minSizeRadioButtonActionPerformed

    private void maxSizeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxSizeRadioButtonActionPerformed
        this.snowflakePanel.setSize(new Dimension(1000, 1000));
    }//GEN-LAST:event_maxSizeRadioButtonActionPerformed

    private void exportPngButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportPngButtonActionPerformed
        if(this.snowflakePanel.getCut() == true){
            JFileChooser exportPng = new JFileChooser();
            FileNameExtensionFilter extension = 
               new FileNameExtensionFilter("PNG (*.png)", "PNG");
            exportPng.setFileFilter(extension);
            exportPng.showDialog(null, "Save");
            try{
                String file = exportPng.getSelectedFile().toPath().toString();
                this.snowflakePanel.createPng(file);
            }catch(NullPointerException | IOException e){
            }
            catch(Exception ex){
            }
        }  
    }//GEN-LAST:event_exportPngButtonActionPerformed

    private void exportSvgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportSvgButtonActionPerformed
         if(this.snowflakePanel.getCut() == true){
           JFileChooser exportSvg = new JFileChooser();
           FileNameExtensionFilter extension = 
                   new FileNameExtensionFilter("SVG (*.svg)", "SVG");
           exportSvg.setFileFilter(extension);
           exportSvg.showDialog(null, "Save");
             try {
                 String file = exportSvg.getSelectedFile().toPath().toString();
                 this.snowflakePanel.createSvg(file);
             } 
             catch (SVGGraphics2DIOException ex) {
             }
             catch(Exception ex){
            
            }
       }
    }//GEN-LAST:event_exportSvgButtonActionPerformed

    private void saveCutPolygonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCutPolygonsActionPerformed
        try {
            this.snowflakePanel.savePoint();
        } catch (IOException ex) {

        }
    }//GEN-LAST:event_saveCutPolygonsActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        this.setVisible(false);
        MainFrame main = new MainFrame();
        main.setVisible(true);
    }//GEN-LAST:event_newButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnowflakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnowflakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnowflakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnowflakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnowflakeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cutButton;
    private javax.swing.JPanel editPanel;
    private javax.swing.JButton exportPngButton;
    private javax.swing.JButton exportSvgButton;
    private javax.swing.JPanel filePanel;
    private javax.swing.JRadioButton maxSizeRadioButton;
    private javax.swing.JTabbedPane menuTabbedPane;
    private javax.swing.JRadioButton minSizeRadioButton;
    private javax.swing.JButton newButton;
    private javax.swing.JButton newPolygonButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveCutPolygons;
    private javax.swing.ButtonGroup sizeButtonGroup;
    private javax.swing.JLabel sizeLabel;
    private Frame.SnowflakePanel snowflakePanel;
    private javax.swing.JLabel typeImageLabel;
    // End of variables declaration//GEN-END:variables
}
